portfolio/urls.py
from django.contrib import admin
from django.urls import path
from personal.views import *
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('power/', admin.site.urls),
    path('', ProjectView, name="project"),
    path('project/<int:pk>/', ProjectDetail, name='project'),
    path('blog', BlogIndex, name='blog'),
    path('blog/<str:pk>/', BlogDetail, name='blog_detail'),
]

urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_on = models.DateField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.CharField(max_length=60)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now=True)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.author

personal/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=30)
    image = models.ImageField(upload_to='project-image', blank=True)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={
            'project_id': self.id
        })

blog/forms.py
from django import forms

class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60, widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Name"
        })
    )

    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Comment"
        }
    ))

blog/views.py
from django.shortcuts import render
from .models import Post,  Comment
from .forms import CommentForm
from django.contrib import messages
# Create your views here.

def BlogIndex(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts": posts,
    }
    return render(request, 'blog_index.html', context)


def BlogDetail(request, pk):
    post = Post.objects.get(pk=pk)
    form = CommentForm()
    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data['author'],
                body=form.cleaned_data['body'],
                post=post
            )
            comment.save()
            messages.success(request, f'{comment.author}! comment submitted succesfully')
    
    comments = Comment.objects.filter(post=post).order_by('-created_on')
    count = Comment.objects.filter(post=post).count()   
    return render(request, 'blog_details.html', {'post': post, 'count': count, 'comments': comments, 'form': form})

personal/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.

def ProjectView(request):
    projects = Project.objects.all()
    context = {
        'projects': projects
    }
    return render(request, 'index.html', context)

def ProjectDetail(request, pk):
    project = Project.objects.get(pk=pk)
    context = {
        'project': project
    }
    return render(request, 'project_detail.html', context)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="{% url 'project' %}">Gpee Portfolio</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'project' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'blog' %}">Blog</a>
                </li>
              </ul>
            </div>
        </div>
    
    </nav>
    
    {% block page %}

    {% endblock %}
</body>
</html>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

templates/blog_details.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% block page %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
</head>

<body>
    <div style="margin-top: 30px;" class="col-md-8 offset-md-2">
        <h5 style="color: teal;">{{ post.title }} </h5><p>{{ post.created_on }}</p>
        <p>{{ post.body }}</p>
    </div>

    <div style="margin-top: 30px;" class="col-md-8 offset-md-2">
        {% for message in messages %}
        <p style="color: #0f0;">{{ message }}</p>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            
            <p>Leave a comment:</p>
            <div style="margin-left: 2px;" class="form-group row">
                <div class="col-xs-3">
                    <input type="text" name="author" class="form-control input-sm" placeholder="Name" maxlength="60" required="" id="id_author">
                </div>
            </div>
    
            <div style="margin-left: 2px;" class="form-group row">
                <div class="col-xs-2">
                    <textarea name="body" cols="22" rows="5" class="form-control" placeholder="Comment" required="" id="id_body"></textarea>
                </div>
            </div>
            
            <div style="margin-left: 2px;" class="form-group row">
                <div class="col-xs-3">
                    <button style="color: teal;" class="btn btn-xs" type="submit">submit</button> 
                </div>         
            </div>

        </form>
    </div>
  
    <div style="margin-top: 30px;" class="col-md-8 offset-md-2">
        
        {% if count <= 1 %}
        <p>{{ count }} comment on {{ post.title }}</p>
        {% else %}
        <p>{{ count }} comments on {{ post.title }}</p>
        {% endif %}
        <p>Comments:</p>
        {% for comment in comments %}
        <div>
            <p style="color: teal">{{ comment.author }}</p>
            <p>{{ comment.created_on|timesince }} ago</p>
            <p>{{ comment.body }}</p>
        </div><hr>
        {% endfor %}
    </div>

</body>
</html>

{% endblock %}

templates/blog_index.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% block page %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>blog index</title>
</head>

<body>
    <div style=" margin-top: 10px" class="col-md-8 offset-md-2">
        <h4>post</h4>
        <hr>
        {% for post in posts %}
        <a style="text-decoration: none; font-size: 20px; color: teal" href="{% url 'blog_detail' post.pk %}">{{ post.title }}</a><br>  
        <small>
            {{ post.created_on }}
        </small><hr>
        {% endfor %}
    </div>
</body>
</html>

{% endblock %}

templates/index.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load static %}

{% block page %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h4 style="margin-top: 20px;" class="container">Projects</h4>
    <div class="row">   
    {% for project in projects %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img style="width: 200px; height: 150px; margin-left: 15px" class="card-img-top" src="{{ project.image.url }}">
                <!--<img style="width: 400px; height: 200px; margin-left: 15px" class="card-img-top" src="{% static 'media/image1.jpg' %}">-->
                <div class="card-body">
                    <h5 class="card-title">{{ project.title }}</h5>
                    <p class="card-text">{{ project.description | slice:"400" }}</p>
                    <a href="{{ project.url }}">{{ project.url }}</a><br><br>
                    <a href="{% url 'project' project.pk %}" class="btn btn-primary">Read More</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</body>
</html>

{% endblock %}

templates/project_detail.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}

{% block page %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Project Details</title>
</head>
<body>
<div class="container-fluid">
    <h3>{{ project.title }}</h3>
    <div class="row">
        <div class="col-md-8">
            <img src="{% static project.image %}" alt="" width="100%">
        </div>
        <div class="col-md-4">
            <h5>About the project:</h5>
            <p>{{ project.description }}</p>
            <br>
            <h5>Technology used:</h5>
            <p style="color: teal;">{{ project.technology }}</p>
        </div>
    </div>
</div>  

</body>
</html>



{% endblock %}